// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-fill-fourth': string;
  'color-fill-primary': string;
  'color-fill-secondary': string;
  'color-fill-tertiary': string;
  'color-stroke-primary': string;
  'color-stroke-secondary': string;
  'color-stroke-tertiary': string;
  'root': string;
  'size-14': string;
  'size-16': string;
  'size-20': string;
  'size-24': string;
}
export const cssExports: CssExports;
export default cssExports;
