// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-primary': string;
  'color-secondary': string;
  'color-tertiary': string;
  'name-copy': string;
  'name-info': string;
  'name-login': string;
  'name-logout': string;
  'name-outer-link': string;
  'name-sun': string;
}
export const cssExports: CssExports;
export default cssExports;
