// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'align-between': string;
  'align-center': string;
  'align-end': string;
  'align-self-end': string;
  'align-start': string;
  'align-stretch': string;
  'direction-column': string;
  'direction-row': string;
  'grow-1': string;
  'grow-2': string;
  'justify-between': string;
  'justify-center': string;
  'justify-end': string;
  'justify-start': string;
  'justify-stretch': string;
  'margin-0-0-16-0': string;
  'margin-0-0-24-0': string;
  'padding-0-0-0-0': string;
  'padding-0-0-12-0': string;
  'padding-0-0-16-0': string;
  'padding-0-0-20-0': string;
  'padding-0-0-24-0': string;
  'padding-0-0-4-0': string;
  'padding-0-0-8-0': string;
  'padding-0-16': string;
  'padding-16-0': string;
  'padding-16-20': string;
  'padding-20': string;
  'padding-20-24': string;
  'padding-24-20': string;
  'padding-32-0': string;
  'padding-40-0': string;
  'padding-40-20': string;
  'spacing-bottom-12': string;
  'spacing-bottom-16': string;
  'spacing-bottom-2': string;
  'spacing-bottom-24': string;
  'spacing-bottom-32': string;
  'spacing-bottom-4': string;
  'spacing-bottom-48': string;
  'spacing-bottom-8': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
