// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fullWidth': string;
  'inner': string;
  'isActive': string;
  'tabButton': string;
  'tabPanel': string;
  'tabPanelActive': string;
  'textTab': string;
  'textTabs': string;
}
export const cssExports: CssExports;
export default cssExports;
