// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'align-center': string;
  'align-left': string;
  'align-right': string;
  'color-black': string;
  'color-primary': string;
  'color-secondary': string;
  'color-tertiary': string;
  'color-white': string;
  'noWrap': string;
  'root': string;
  'spacingBottom-12': string;
  'spacingBottom-24': string;
  'spacingBottom-32': string;
  'spacingBottom-8': string;
  'uppercase': string;
  'weight-bold': string;
  'weight-semibold': string;
}
export const cssExports: CssExports;
export default cssExports;
