// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'body': string;
  'cross': string;
  'hasModal': string;
  'header': string;
  'modal': string;
  'root': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
