// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'body': string;
  'modal': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
