// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clickable': string;
  'root': string;
  'squareSize-100%': string;
  'squareSize-32': string;
}
export const cssExports: CssExports;
export default cssExports;
