// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'h1': string;
  'h4': string;
  'link': string;
  'sectionSubtitle': string;
  'sectionTitle': string;
  'typeface-header-32': string;
  'typeface-header-44': string;
  'typeface-paragraph-14': string;
  'typeface-paragraph-16': string;
  'typeface-paragraph-20': string;
  'typeface-title-14': string;
  'typeface-title-16': string;
  'typeface-title-20': string;
  'typeface-title-24': string;
  'typeface-title-28': string;
}
export const cssExports: CssExports;
export default cssExports;
